kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "hacksploit.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "hacksploit.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "hacksploit.fullname" . }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io